In [61]:
import mmcv
from mmcv import Config
import torch

In [62]:
a = [1,2]
print('%s'%(a))

[1, 2]


In [59]:
a = []

for i in range(10):
    a.append(torch.rand((1,2)))

b = [a[i] for i in range(2,5)]

a[2] = 2*a[2]
a, b

([tensor([[0.4295, 0.1855]]),
  tensor([[0.4797, 0.5900]]),
  tensor([[0.8507, 0.3484]]),
  tensor([[0.2414, 0.1799]]),
  tensor([[0.6218, 0.5239]]),
  tensor([[0.2186, 0.3749]]),
  tensor([[0.3524, 0.5366]]),
  tensor([[0.8011, 0.0404]]),
  tensor([[0.3856, 0.6175]]),
  tensor([[0.8821, 0.4285]])],
 [tensor([[0.4254, 0.1742]]),
  tensor([[0.2414, 0.1799]]),
  tensor([[0.6218, 0.5239]])])

In [60]:
a = torch.rand((2,3,3))
a, a.permute(0,2,1)

(tensor([[[0.9294, 0.2869, 0.9446],
          [0.5648, 0.0686, 0.6935],
          [0.1668, 0.3442, 0.6215]],
 
         [[0.6576, 0.2144, 0.2884],
          [0.6934, 0.9466, 0.4805],
          [0.8072, 0.6416, 0.3716]]]),
 tensor([[[0.9294, 0.5648, 0.1668],
          [0.2869, 0.0686, 0.3442],
          [0.9446, 0.6935, 0.6215]],
 
         [[0.6576, 0.6934, 0.8072],
          [0.2144, 0.9466, 0.6416],
          [0.2884, 0.4805, 0.3716]]]))

In [27]:
layers = [i for i in range(8, 17)]
', '.join(str(i) for i in layers)

'8, 9, 10, 11, 12, 13, 14, 15, 16'

In [43]:
cfg = Config.fromfile('./configs/train_strongce.py')

In [51]:
for i in cfg.loss.match_layers:
    print(cfg.model.backbone.layers.index(i))

0
1
2
3
4
5
6
7
8


In [41]:
cfg.model.backbone.cam

''

In [10]:
for key in cfg.__dict__:
    print(key)

_cfg_dict
_filename
_text
